const productos = [
    {
        nombre: 'Base Atenea',
        descripcionCorta: 'Base profesional alta cobertura con FPS 15',
        precio: 58000,
        precioAnterior: 68000,
        imagenes: [{ url: '/img/productos/base-atenea.webp', posicion: 'center 80%', esPrincipal: true }],
        marca: { nombre: 'Atenea Profesional' },
        destacado: true,
        enPromocion: true,
    },
    {
        nombre: 'Corrector Atenea',
        descripcionCorta: 'Corrector alta cobertura con vitamina E',
        precio: 38000,
        imagenes: [{ url: '/img/productos/corrector-atenea.webp', posicion: 'center 50%', esPrincipal: true }],
        marca: { nombre: 'Atenea Profesional' },
        destacado: true,
    },
    {
        nombre: "Base Matte L'Bel",
        descripcionCorta: 'Base matte larga duración control brillo',
        precio: 62000,
        imagenes: [{ url: '/img/productos/base-matte-lbel.webp', posicion: 'center 50%', esPrincipal: true }],
        marca: { nombre: "L'Bel" },
    },
    {
        nombre: 'Sombras Atenea',
        descripcionCorta: 'Paleta 9 sombras mate y shimmer',
        precio: 45000,
        precioAnterior: 55000,
        imagenes: [{ url: '/img/productos/sombras-atenea.webp', posicion: 'center 50%', esPrincipal: true }],
        marca: { nombre: 'Atenea Profesional' },
        destacado: true,
        enPromocion: true,
    },
    {
        nombre: 'Delineador en Gel JDG',
        descripcionCorta: 'Delineador gel resistente al agua',
        precio: 34000,
        imagenes: [{ url: '/img/productos/delineador-en-gel-jdg.webp', posicion: 'center 90%', esPrincipal: true }],
        marca: { nombre: 'Jorge de la Garza' },
    },
    {
        nombre: 'Lip Gloss',
        descripcionCorta: 'Gloss hidratante efecto volumen',
        precio: 32000,
        imagenes: [{ url: '/img/productos/lip-gloss.webp', posicion: '30% 75%', esPrincipal: true }],
        marca: { nombre: 'Atenea Profesional' },
        destacado: true,
    },
    {
        nombre: "Labial Mate L'Bel",
        descripcionCorta: 'Labial mate larga duración confortable',
        precio: 36000,
        precioAnterior: 42000,
        imagenes: [{ url: '/img/productos/labial-mate-lbl.webp', posicion: 'center 90%', esPrincipal: true }],
        marca: { nombre: "L'Bel" },
        enPromocion: true,
    },
    {
        nombre: 'Shampoo Hidratación Profunda',
        descripcionCorta: 'Shampoo con keratina, argán y aloe vera',
        precio: 46000,
        precioAnterior: 52000,
        imagenes: [{ url: '/img/productos/shampoo-hidratacion-profunda.webp', esPrincipal: true }],
        marca: { nombre: 'Atenea Profesional' },
        destacado: true,
        enPromocion: true,
    },
    {
        nombre: "Shampoo Anticaída L'Bel",
        descripcionCorta: 'Shampoo anticaída fortalecedor',
        precio: 52000,
        imagenes: [{ url: '/img/productos/shampoo-anti-caida.webp', esPrincipal: true }],
        marca: { nombre: "L'Bel" },
    },
    {
        nombre: 'Shampoo Nutritivo JDG',
        descripcionCorta: 'Shampoo nutritivo proteínas de seda',
        precio: 41000,
        imagenes: [{ url: '/img/productos/shampoo-nutritivo.webp', esPrincipal: true }],
        marca: { nombre: 'Jorge de la Garza' },
    },
    {
        nombre: 'Acondicionador Reparador',
        descripcionCorta: 'Acondicionador reparador sella cutículas',
        precio: 46000,
        imagenes: [{ url: '/img/productos/acondicionador-reparador.webp', esPrincipal: true }],
        marca: { nombre: 'Atenea Profesional' },
    },
    {
        nombre: "Acondicionador Nutrición Intensa L'Bel",
        descripcionCorta: 'Acondicionador nutrición intensa cabello seco',
        precio: 50000,
        imagenes: [{ url: '/img/productos/acondicionador-nutricion-intensa.webp', esPrincipal: true }],
        marca: { nombre: "L'Bel" },
    },
    {
        nombre: 'Tratamiento Control de Frizz',
        descripcionCorta: 'Tratamiento anti-frizz con keratina',
        precio: 58000,
        imagenes: [{ url: '/img/productos/tratamiento-control-de-frizz.webp', esPrincipal: true }],
        marca: { nombre: 'Atenea Profesional' },
        destacado: true,
    },
    {
        nombre: 'Ampolletas de Keratina JDG',
        descripcionCorta: 'Ampolletas keratina tratamiento intensivo',
        precio: 39000,
        imagenes: [{ url: '/img/productos/keratina-ampolleta.webp', posicion: 'center 70%', esPrincipal: true }],
        marca: { nombre: 'Jorge de la Garza' },
    },
    {
        nombre: 'Paleta de Sombras Nude',
        descripcionCorta: 'Paleta de sombras en tonos nude',
        precio: 45000,
        precioAnterior: 58000,
        imagenes: [{ url: '/img/promociones/paleta-de-sombras.webp', esPrincipal: true }],
        marca: { nombre: 'Atenea Profesional' },
        destacado: true,
        enPromocion: true,
    },
    {
        nombre: 'Labial Mate Larga Duración',
        descripcionCorta: 'Labial mate de alta fijación hasta 12 horas',
        precio: 29000,
        precioAnterior: 38000,
        imagenes: [{ url: '/img/promociones/labial-mate.webp', posicion: 'center 65%', esPrincipal: true }],
        marca: { nombre: "L'Bel" },
        destacado: true,
        enPromocion: true,
    },
];

export const FALLBACK_FEATURED = productos.filter(producto => producto.destacado);
export const FALLBACK_PROMOS = productos.filter(producto => producto.enPromocion);
export const FALLBACK_CATALOG = {
    rostro: productos.filter(producto => /Base|Corrector/.test(producto.nombre)),
    ojos: productos.filter(producto => /Sombras|Delineador/.test(producto.nombre)),
    labios: productos.filter(producto => /Labial|Gloss/.test(producto.nombre)),
    shampoo: productos.filter(producto => /Shampoo/.test(producto.nombre)),
    acondicionador: productos.filter(producto => /Acondicionador/.test(producto.nombre)),
    tratamientos: productos.filter(producto => /Tratamiento|Ampolletas/.test(producto.nombre)),
};
